### ISSUE TITLE
Cannot find module 'express-busboy'_hooked.js:

### ISSUE THREAD

**Issue by wcross89** [bipinswarnkar1989/mean_stack_tutorial_todo_app#3]
On ... npm start
[nodemon] starting `node app_hooked.js`
module.js:549
    throw err;
    ^
b\mean_stack_tutorial_todo_app\express-server\ap
prror: Cannot find module 'express-busboy'_hooked.js:5:1)
    at Module._compile (module.js:652:30)    at Object.Module._extensions..js (module.js:
6   at Function.Module._load (module.js:474:25)
63:10)

**Comment by wcross89** [comment]
Added this comand before running npm start
> **npm install express-busboy**

I think you could do this as well ...
>npm install body-parser mongoose morgan babel-preset-es2015-node6 **express-busboy** source-map-support --save
